var Plotly = require('@lib');
var Lib = require('@src/lib');

var d3 = require('d3');
var createGraphDiv = require('../assets/create_graph_div');
var fail = require('../assets/fail_test');
var subplotMock = require('@mocks/multiple_subplots.json');


describe('Plotly.toImage', function() {
    'use strict';

    var gd;

    beforeEach(function() {
        gd = createGraphDiv();
    });

    afterEach(function() {

        // make sure ALL graph divs are deleted,
        // even the ones generated by Plotly.toImage
        d3.selectAll('.js-plotly-plot').remove();
        d3.selectAll('#graph').remove();
    });

    function createImage(url) {
        return new Promise(function(resolve, reject) {
            var img = document.createElement('img');
            img.src = url;
            img.onload = function() { return resolve(img); };
            img.onerror = function() { return reject('error during createImage'); };
        });
    }

    it('should be attached to Plotly', function() {
        expect(Plotly.toImage).toBeDefined();
    });

    it('should return a promise', function(done) {
        function isPromise(x) {
            return !!x.then && typeof x.then === 'function';
        }

        var returnValue = Plotly.plot(gd, subplotMock.data, subplotMock.layout)
               .then(Plotly.toImage);

        expect(isPromise(returnValue)).toBe(true);

        returnValue.then(done);
    });

    it('should throw error with unsupported file type', function(done) {
        // error should actually come in the svgToImg step

        Plotly.plot(gd, subplotMock.data, subplotMock.layout)
            .then(function(gd) {
                Plotly.toImage(gd, {format: 'x'}).catch(function(err) {
                    expect(err.message).toEqual('Image format is not jpeg, png or svg');
                    done();
                });
            });

    });

    it('should throw error with height and/or width < 1', function(done) {
        // let user know that Plotly expects pixel values
        Plotly.plot(gd, subplotMock.data, subplotMock.layout)
            .then(function(gd) {
                return Plotly.toImage(gd, {height: 0.5}).catch(function(err) {
                    expect(err.message).toEqual('Height and width should be pixel values.');
                });
            }).then(function() {
                Plotly.toImage(gd, {width: 0.5}).catch(function(err) {
                    expect(err.message).toEqual('Height and width should be pixel values.');
                    done();
                });
            });
    });

    it('should create img with proper height and width', function(done) {
        var fig = Lib.extendDeep({}, subplotMock);

        // specify height and width
        fig.layout.height = 600;
        fig.layout.width = 700;

        Plotly.plot(gd, fig.data, fig.layout).then(function(gd) {
            expect(gd.layout.height).toBe(600);
            expect(gd.layout.width).toBe(700);
            return Plotly.toImage(gd);
        })
        .then(createImage)
        .then(function(img) {
            expect(img.height).toBe(600);
            expect(img.width).toBe(700);

            return Plotly.toImage(gd, {height: 400, width: 400});
        })
        .then(createImage)
        .then(function(img) {
            expect(img.height).toBe(400);
            expect(img.width).toBe(400);
        })
        .catch(fail)
        .then(done);
    });

    it('should create proper file type', function(done) {
        var fig = Lib.extendDeep({}, subplotMock);

        Plotly.plot(gd, fig.data, fig.layout)
        .then(function() { return Plotly.toImage(gd, {format: 'png'}); })
        .then(function(url) {
            expect(url.split('png')[0]).toBe('data:image/');
        })
        .then(function() { return Plotly.toImage(gd, {format: 'jpeg'}); })
        .then(function(url) {
            expect(url.split('jpeg')[0]).toBe('data:image/');
        })
        .then(function() { return Plotly.toImage(gd, {format: 'svg'}); })
        .then(function(url) {
            expect(url.split('svg')[0]).toBe('data:image/');
        })
        .then(function() { return Plotly.toImage(gd, {format: 'webp'}); })
        .then(function(url) {
            expect(url.split('webp')[0]).toBe('data:image/');
        })
        .catch(fail)
        .then(done);
    });
});
