/**
* Copyright 2012-2017, Plotly, Inc.
* All rights reserved.
*
* This source code is licensed under the MIT license found in the
* LICENSE file in the root directory of this source tree.
*/


'use strict';

module.exports = {
    'circle': '●',
    'circle-open': '○',
    'square': '■',
    'square-open': '□',
    'diamond': '◆',
    'diamond-open': '◇',
    'cross': '✚',
    'triangle-up': '▲',
    'triangle-up-open': '△',
    'triangle-down': '▼',
    'triangle-down-open': '▽',
    'triangle-left': '◄',
    'triangle-left-open': '◁',
    'triangle-right': '►',
    'triangle-right-open': '▷',
    'triangle-ne': '◥',
    'triangle-ne-open': '◹',
    'triangle-nw': '◤',
    'triangle-nw-open': '◸',
    'triangle-se': '◢',
    'triangle-se-open': '◿',
    'triangle-sw': '◣',
    'triangle-sw-open': '◺',
    'pentagon': '⬟',
    'pentagon-open': '⬠',
    'hexagon': '⬢',
    'hexagon-open': '⬡',
    'hexagon2': '⬣',
    'star': '★',
    'star-open': '☆',
    'diamond-tall': '♦',
    'diamond-tall-open': '♢',
    'diamond-wide': '▰',
    'diamond-wide-open': '▱',
    'bowtie': '⧓',
    'bowtie-open': '⋈',
    'circle-cross': '⨁',
    'circle-x': '⨂',
    'square-cross': '⊞',
    'square-x': '⊠',
    'diamond-cross': '⟠',
    'diamond-x': '❖',
    'cross-thin': '+',
    'cross-thin-open': '+',
    'x-thin': '╳',
    'x-thin-open': '╳',
    'asterisk': '✳',
    'asterisk-open': '✳',
    'y-up': '⅄',
    'y-up-open': '⅄',
    'y-down': 'Y',
    'y-down-open': 'Y',
    'y-left': '≺',
    'y-left-open': '≺',
    'y-right': '≻',
    'y-right-open': '≻',
    'line-ew': '─',
    'line-ew-open': '─',
    'line-ns': '│',
    'line-ns-open': '│',
    'line-ne': '╱',
    'line-ne-open': '╱',
    'line-nw': '╲',
    'line-nw-open': '╲'
};
