/**
* Copyright 2012-2017, Plotly, Inc.
* All rights reserved.
*
* This source code is licensed under the MIT license found in the
* LICENSE file in the root directory of this source tree.
*/


'use strict';

// N.B. HTML entities are listed without the leading '&' and trailing ';'

module.exports = {

    entityToUnicode: {
        'alefsym': 'ℵ',
        'Alpha': 'Α',
        'alpha': 'α',
        'amp': '&',
        'and': '∧',
        'ang': '∠',
        'asymp': '≈',
        'Beta': 'Β',
        'beta': 'β',
        'bull': '•',
        'cap': '∩',
        'Chi': 'Χ',
        'chi': 'χ',
        'clubs': '♣',
        'cong': '≅',
        'crarr': '↵',
        'cup': '∪',
        'darr': '↓',
        'dArr': '⇓',
        'deg': '°',
        'Delta': 'Δ',
        'delta': 'δ',
        'diams': '♦',
        'empty': '∅',
        'Epsilon': 'Ε',
        'epsilon': 'ε',
        'equiv': '≡',
        'Eta': 'Η',
        'eta': 'η',
        'exist': '∃',
        'fnof': 'ƒ',
        'forall': '∀',
        'frasl': '⁄',
        'Gamma': 'Γ',
        'gamma': 'γ',
        'ge': '≥',
        'gt': '>',
        'harr': '↔',
        'hArr': '⇔',
        'hearts': '♥',
        'hellip': '…',
        'image': 'ℑ',
        'infin': '∞',
        'int': '∫',
        'Iota': 'Ι',
        'iota': 'ι',
        'isin': '∈',
        'Kappa': 'Κ',
        'kappa': 'κ',
        'Lambda': 'Λ',
        'lambda': 'λ',
        'lang': '⟨',
        'larr': '←',
        'lArr': '⇐',
        'lceil': '⌈',
        'le': '≤',
        'lfloor': '⌊',
        'lt': '<',
        'lowast': '∗',
        'loz': '◊',
        'minus': '−',
        'Mu': 'Μ',
        'mu': 'μ',
        'nabla': '∇',
        'nbsp': ' ',
        'ne': '≠',
        'ni': '∋',
        'notin': '∉',
        'nsub': '⊄',
        'Nu': 'Ν',
        'nu': 'ν',
        'oline': '‾',
        'Omega': 'Ω',
        'omega': 'ω',
        'Omicron': 'Ο',
        'omicron': 'ο',
        'oplus': '⊕',
        'or': '∨',
        'otimes': '⊗',
        'part': '∂',
        'perp': '⊥',
        'Phi': 'Φ',
        'phi': 'φ',
        'Pi': 'Π',
        'pi': 'π',
        'piv': 'ϖ',
        'plusmn': '±',
        'prime': '′',
        'Prime': '″',
        'prod': '∏',
        'prop': '∝',
        'Psi': 'Ψ',
        'psi': 'ψ',
        'radic': '√',
        'rang': '⟩',
        'rarr': '→',
        'rArr': '⇒',
        'rceil': '⌉',
        'real': 'ℜ',
        'rfloor': '⌋',
        'Rho': 'Ρ',
        'rho': 'ρ',
        'sdot': '⋅',
        'Sigma': 'Σ',
        'sigma': 'σ',
        'sigmaf': 'ς',
        'sim': '∼',
        'spades': '♠',
        'sub': '⊂',
        'sube': '⊆',
        'sum': '∑',
        'sup': '⊃',
        'supe': '⊇',
        'Tau': 'Τ',
        'tau': 'τ',
        'there4': '∴',
        'Theta': 'Θ',
        'theta': 'θ',
        'times': '×',
        'thetasym': 'ϑ',
        'trade': '™',
        'uArr': '⇑',
        'upsih': 'ϒ',
        'Upsilon': 'Υ',
        'upsilon': 'υ',
        'weierp': '℘',
        'Xi': 'Ξ',
        'xi': 'ξ',
        'Zeta': 'Ζ',
        'zeta': 'ζ'
    },

    unicodeToEntity: {
        '&': 'amp',
        '<': 'lt',
        '>': 'gt',
        '"': 'quot',
        '\'': '#x27',
        '\/': '#x2F'
    }

};
