source 'https://rubygems.org'
gem 'github-pages'
gem 'jekyll-redirect-from'
gem 'jemoji'
gem 'octopress'
gem 'rake'
gem 'jekyll-sitemap'
gem 'percy-cli'
gem 'webrick'

group :jekyll_plugins do
  gem 'octopress-debugger'
end

group :jekyll_plugins do
  gem 'algoliasearch-jekyll', '~> 0.8.2'
end
